// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akcjljmgdoojrxkcsxao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrY2psam1nZG9vanJ4a2NzeGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMTEwODEsImV4cCI6MjA2MTg4NzA4MX0.hvcTTMl_RITN5MvkitHKxj0fNXV-Feujiaxl236OUYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);